# Default values for kibana.
# Service
name: kibana-logging
app: kibana-logging
port: 5601
# Deployment
component: kibana-logging
replicas: 3
container_name: kibana-logging
image: quay.io/samsung_cnct/kibana-container:latest
# keep request = limit to keep this container in guaranteed class
cpu_limit: 100m
cpu_requests: 100m
env_name: ELASTICSEARCH_URL
env_value: http://elasticsearch:9200
container_port: 5601
tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule

scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]